# Generated by Django 3.2.4 on 2021-12-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
