# Generated by Django 3.2.4 on 2021-12-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_auto_20211220_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='chat_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
